### ISSUE TITLE
an error occurred when running "DGSQP-main\scripts\process_data_comp.py"

### ISSUE THREAD

**Issue by szyvcdc** [zhu-edward/DGSQP#1]
Dear edward zhu

This part of the open source code helps me a lot, thank you very much. I have a problem and I want your help, that is, an error occurred when running "DGSQP-main\scripts\process_data_comp.py"(from mpclab_common.track import get_track), it tells me"ModuleNotFoundError: No module named mpclab_common", It would be grateful if you could let me know any further information at your earliest convenience.

With best regards!

Yours sincerely

**Comment by zhu-edward** [comment]
Thanks for pointing this out. I've fixed the script to import from the `get_track` function from the `DGSQP` package instead of `mpclab_common`.
